// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibjxncbjjqrznozsmoap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlianhuY2JqanFyem5venNtb2FwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYzNDAxOTQsImV4cCI6MjA1MTkxNjE5NH0.49AtUt2pcl81090foX0egIMzThktATPoDh6ybuoQ-Ec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);